# Generated by Django 4.2.7 on 2026-06-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_plate',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car')], default='motorcycle', max_length=50),
        ),
    ]
