# Generated by Django 4.2.7 on 2026-06-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driverprofile_vehicle_plate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='driver_license',
            field=models.ImageField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_ids/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos/'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='business_licenses/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='seller_ids/'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller_photos/'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('car', 'Car'), ('van', 'Van'), ('truck', 'Truck')], default='motorcycle', max_length=50),
        ),
    ]
