# Generated by Django 4.2.7 on 2026-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_driverprofile_driver_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='driver_license',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='national_id_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='business_license',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='national_id_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
