# Generated by Django 4.2.7 on 2026-06-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of seller/restaurant', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of seller/restaurant', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of delivery address', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of delivery address', max_digits=9, null=True),
        ),
    ]
