# Generated by Django 4.2.7 on 2026-06-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_delivery_instructions_order_seller_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_address',
            field=models.CharField(blank=True, help_text='Address of the seller/restaurant', max_length=255, null=True),
        ),
    ]
